---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: alertmanager-main
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by:
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15s
      receiver: slack-notifications
      routes:
      - receiver: slack-notifications
        match:
          severity: warning
    receivers:
    - name: slack-notifications
      slack_configs:
      - channel: "#alerts"
        send_resolved: true
        api_url: "https://hooks.slack.com/services/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"
        text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
