---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: default
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Main
      type: prometheus
      url: http://prometheus-operated.monitoring:9090
      isDefault: false
      jsonData:
        manageAlerts: false
