apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: iqa-prom-svc
  labels:
    app: iqa-monitoring
spec:
  selector:
    app: iqa-app
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 1234
      targetPort: http-metrics
