---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: node-exporter
  # labels:
  #   name: node-exporter
  #   kubernetes.io/cluster-service: "true"
  #   addonmanager.kubernetes.io/mode: Reconcile
  #   version: v0.15.2
spec:
  selector:
    matchLabels:
      name: node-exporter
      # version: v0.18.1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        name: node-exporter
        # version: v0.18.1
    spec:
      containers:
        - name: node-exporter
          image: "prom/node-exporter:latest"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: http
              containerPort: 9100
              protocol: TCP
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
