---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: node-exporter
  labels:
    name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9100
    targetPort: http
  selector:
    name: node-exporter
