deploy:
  name: iqa-app
  weight: 0
  replicas: 1
  container:
    image:
      repository: longpk1/iqa_v2_1
      tag: 1.5.7
      imagePullPolicy: Always
    volumeMounts:
      tempPath: /app/static/temp
      dataPath: /app/userdata
    port_ui: 6789
    port_metrics: 1234
  claimName: iqa-filestore

svc:
  name: iqa-svc
  weight: 1
  type: ClusterIP
  port: 6789
  targetPort: 6789

prom_svc:
  name: iqa-prom-svc
  type: ClusterIP
  port: 1234
  targetPort: 1234
