apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.sc.name }}
  annotations:
    werf.io/weight: "{{ .Values.sc.weight }}"
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default
