apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  annotations:
    werf.io/weight: "{{ .Values.deploy.name }}"
spec:
  selector:
    app: {{ .Values.svc.name }}
  type: {{ .Values.svc.type }}
  ports:
    - name: minio-ui
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: minio-backend
      protocol: TCP
      port: 9000
      targetPort: 9000
